server:
  port: 8881

############################################################
#
#   zookeeper连接信息
#
#
############################################################
elastic:
  job:
    zk:
      serverLists: phy1:2181
      namespace: esjob-task
      connection-timeout-milliseconds: 10000
      session-timeout-milliseconds: 10000
      max-retries: 3

############################################################
#
#   simpleJob的配置信息
#
#
############################################################
#simpleJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 5
#  shardingItemParameters: 0=beijing,1=shanghai,2=changchun,3=changsha,4=hangzhou
#  jobParameter: source1=public,source2=private
#  failover: true
#  monitorExecution: true
#  monitorPort: 8889
#  maxTimeDiffSeconds: -1
#  jobShardingStrategyClass: com.dangdang.ddframe.job.lite.api.strategy.impl.AverageAllocationJobShardingStrategy

############################################################
#
#   Spring自带数据库连接池
#
#
############################################################
spring:
  datasource:
    url: jdbc:mysql://phy1:3306/test?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zchuang
