server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://local:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: zchuang